# Generated by Django 6.1.1 on 2026-09-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, unique=True)),
                ('disease_display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('treatment', models.TextField()),
                ('treatment_duration', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
